export const SET_TOKEN = "SET_TOKEN";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const SET_CANGE_MAIN_PAGE = "SET_CANGE_MAIN_PAGE";
export const SET_CANGE_EXAM_PART = "SET_CANGE_EXAM_PART";
export const SET_CANGE_CURRENT_PART = "SET_CANGE_CURRENT_PART";

export const SET_BLOCK = "SET_BLOCK";
export const SET_TIMER = "SET_TIMER";
export const SET_RESET_TIMER = "SET_RESET_TIMER";
export const RESET_TIMER = "RESET_TIMER";

export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SET_QUESTION_PART = "SET_QUESTION_PART";
export const SET_QUESTION = "SET_QUESTION";
export const SET_INITIAL = "SET_INITIAL";

export const SET_INITIAL_PAGE_BY_ROLE = "SET_INITIAL_PAGE_BY_ROLE";
export const SET_INITIAL_STATE = "SET_INITIAL_STATE";
export const SET_STUDENTS = "SET_STUDENTS";
export const SET_TEACHERS = "SET_TEACHERS";
export const SET_OPERATORS = "SET_OPERATORS";
export const SET_STUDENTS_ID = "SET_STUDENTS_ID";
export const SET_ANSWER = "SET_ANSWER";

export const SET_AUTH_ERROR = "SET_AUTH_ERROR";
export const SET_LOADER = "SET_LOADER";
