export const SET_TOKEN = 'SET_TOKEN';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SET_INITIAL_AUTH = 'SET_INITIAL_AUTH';

export const SET_CANGE_MAIN_PAGE = 'SET_CANGE_MAIN_PAGE';
export const SET_CANGE_EXAM_PART = 'SET_CANGE_EXAM_PART';
export const SET_CANGE_CURRENT_PART = 'SET_CANGE_CURRENT_PART';

export const SET_BLOCK = 'SET_BLOCK';
export const SET_TIMER = 'SET_TIMER';
export const SET_RESET_TIMER = 'SET_RESET_TIMER';
export const RESET_TIMER = 'RESET_TIMER';
export const SET_INITIAL_EXAM = 'SET_INITIAL_EXAM';

export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_QUESTION_PART = 'SET_QUESTION_PART';
export const SET_QUESTION = 'SET_QUESTION';
export const SET_INITIAL_PAGE = 'SET_INITIAL_PAGE';

export const SET_INITIAL_PAGE_BY_ROLE = 'SET_INITIAL_PAGE_BY_ROLE';
export const SET_INITIAL_ADMIN = 'SET_INITIAL_ADMIN';
export const SET_STUDENTS = 'SET_STUDENTS';
export const SET_TEACHERS = 'SET_TEACHERS';
export const SET_OPERATORS = 'SET_OPERATORS';
export const SET_STUDENTS_ID = 'SET_STUDENTS_ID';
export const SET_ANSWER = 'SET_ANSWER';
export const SET_ALL_BLOCK = 'SET_ALL_BLOCK';
export const UPDATE_USERS = 'UPDATE_USERS';
export const ADD_BLOCK = 'ADD_BLOCK';
export const UPDATE_BLOCK = 'UPDATE_BLOCK';
export const GET_BLOCK = 'GET_BLOCK';
export const DELETE_BLOCK = 'DELETE_BLOCK';
export const SET_SUB_PAGE = 'SET_SUB_PAGE';
export const ADD_USER_IN_TABLE = 'ADD_USER_IN_TABLE';
export const SET_MODAL = 'SET_MODAL';

export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';
export const SET_USER_CREATE_ERROR = 'SET_USER_CREATE_ERROR';
export const SET_BLOK_CREATE_ERROR = 'SET_BLOK_CREATE_ERROR';
export const SET_BLOK_DELETE_ERROR = 'SET_BLOK_DELETE_ERROR';

export const SET_LOADER = 'SET_LOADER';
export const SET_INITIAL_ERROR = 'SET_INITIAL_ERROR';
